### ISSUE TITLE
error downloading QM qm8 E1-PBE0 E2-PBE0 f1-PBE0 f2-PBE0

### ISSUE THREAD

**Issue by markmoraes** [mims-harvard/TDC#143]
Hi.

Using TDC cloned from github commit 3ebda027e09694a68c0ac627f44948cab7a80193
I see the following error (and nested error) when trying to load a few `QM` `qm8` labels, namely:
```
QM  qm8 E1-PBE0
QM  qm8 E2-PBE0
QM  qm8 f1-PBE0
QM  qm8 f2-PBE0
```
Other datasets (QM qm8 *-CC2, *-CAM, or ADME, Tox etc) download fine.

I'm using `Python 3.7.7` (compiled locally) with `fuzzywuzzy-0.17.0-py2.py3-none-any.whl` 
`CentOS Linux release 7.7.1908 (Core)`

```
from tdc.utils import retrieve_label_name_list
label_list = retrieve_label_name_list('QM8')
label_list

['E1-CC2', 'E2-CC2', 'f1-CC2', 'f2-CC2', 'E1-PBE0', 'E2-PBE0', 'f1-PBE0', 'f2-PBE0', 'E1-PBE0', 'E2-PBE0', 'f1-PBE0', 'f2-PBE0', 'E1-CAM', 'E2-CAM', 'f1-CAM', 'f2-CAM']

from tdc.single_pred import QM
data = QM(name = 'QM8', label_name = 'E1-PBE0')

Downloading...
100%|\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 122M/122M [00:06<00:00, 18.5MiB/s]
Loading...
Traceback (most recent call last):
  File "/data/therapeutic_data_commons/tdc/utils/load.py", line 241, in property_dataset_load
    df = df[df[target].notnull()].reset_index(drop = True)
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/frame.py", line 2893, in __getitem__
    return self.where(key)
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/generic.py", line 9005, in where
    cond, other, inplace, axis, level, errors=errors, try_cast=try_cast
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/generic.py", line 8845, in _where
    cond = cond.reindex(self._info_axis, axis=self._info_axis_number)
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/util/_decorators.py", line 309, in wrapper
    return func(*args, **kwargs)
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/frame.py", line 4036, in reindex
    return super().reindex(**kwargs)
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/generic.py", line 4462, in reindex
    axes, level, limit, tolerance, method, fill_value, copy
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/frame.py", line 3877, in _reindex_axes
    columns, method, copy, level, fill_value, limit, tolerance
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/frame.py", line 3925, in _reindex_columns
    allow_dups=False,
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/generic.py", line 4530, in _reindex_with_indexers
    copy=copy,
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1276, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/tools/python/3.7.7-06c7/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3289, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/therapeutic_data_commons/tdc/single_pred/qm.py", line 33, in __init__
    dataset_names=dataset_names["QM"], convert_format = convert_format)
  File "/data/therapeutic_data_commons/tdc/single_pred/single_pred_dataset.py", line 55, in __init__
    entity1, y, entity1_idx = property_dataset_load(name, path, label_name, dataset_names)
  File "/data/therapeutic_data_commons/tdc/utils/load.py", line 244, in property_dataset_load
    flag = 'Service Unavailable' in ' '.join(f.readlines())
  File "/tools/python/3.7.7-06c7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
>>> 
```

Regards,
Mark.

**Comment by futianfan** [comment]
i tried the code and met the same error, will fix it soon. thanks

**Comment by futianfan** [comment]
it is fixed. sorry for the delay!
