### ISSUE TITLE
add requests to requirements.txt

### ISSUE THREAD

**Issue by SzilviaKiriakov** [mims-harvard/TDC#156]
I am reproducing the [code from the website](https://tdcommons.ai/single_pred_tasks/develop/#tap) to access the TAP dataset on Python-3.8.5. with pip installation of PyTDC-0.3.6 (macOS), but cannot load the dataset. 

>>> from tdc.utils import retrieve_label_name_list
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".pyenv/versions/python-3.8.5/lib/python3.8/site-packages/tdc/__init__.py", line 1, in <module>
    from .evaluator import Evaluator
  File ".pyenv/versions/python-3.8.5/lib/python3.8/site-packages/tdc/evaluator.py", line 7, in <module>
    from .utils import fuzzy_search 
  File ".pyenv/versions/python-3.8.5/lib/python3.8/site-packages/tdc/utils/__init__.py", line 1, in <module>
    from .load import distribution_dataset_load, \
  File ".pyenv/versions/python-3.8.5/lib/python3.8/site-packages/tdc/utils/load.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I get the same error with SAbDab_Chen dataset.

>>> from tdc.single_pred import Develop
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyenv/versions/python-3.8.5/lib/python3.8/site-packages/tdc/__init__.py", line 1, in <module>
    from .evaluator import Evaluator
  File ".pyenv/versions/python-3.8.5/lib/python3.8/site-packages/tdc/evaluator.py", line 7, in <module>
    from .utils import fuzzy_search 
  File ".pyenv/versions/python-3.8.5/lib/python3.8/site-packages/tdc/utils/__init__.py", line 1, in <module>
    from .load import distribution_dataset_load, \
  File "pyenv/versions/python-3.8.5/lib/python3.8/site-packages/tdc/utils/load.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by SzilviaKiriakov** [comment]
Thank you, that worked. So I assume [here](https://tdc.readthedocs.io/en/main/install.html) `requests` should be listed as an additional dependency, it was just missed.

**Comment by futianfan** [comment]
yes. it is additional.

**Comment by kexinhuang12345** [comment]
yeah i think we probably need to update the requirements.txt.
