### ISSUE TITLE
mistake zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by lightwindcy** [mims-harvard/TDC#311]
**Describe your question.**

when i use follow code

from tdc import BenchmarkGroup
group = BenchmarkGroup(name = 'ADMET_Group', path = 'data/')
predictions_list = []

Downloading Benchmark Group...
0.00iB [00:00, ?iB/s]
Extracting zip file...
Traceback (most recent call last):
  File "E:/pretrain/TopoPool-main/down.py", line 2, in <module>
    group = BenchmarkGroup(name = 'ADMET_Group', path = 'data/')
  File "C:\Users\xjp\anaconda3\envs\pytorch_env\lib\site-packages\tdc\benchmark_deprecated.py", line 96, in __init__
    self.name = bm_group_load(name, path)
  File "C:\Users\xjp\anaconda3\envs\pytorch_env\lib\site-packages\tdc\utils\load.py", line 585, in bm_group_load
    name = bm_download_wrapper(name, path)
  File "C:\Users\xjp\anaconda3\envs\pytorch_env\lib\site-packages\tdc\utils\load.py", line 266, in bm_download_wrapper
    with ZipFile(os.path.join(path, name + ".zip"), "r") as zip:
  File "C:\Users\xjp\anaconda3\envs\pytorch_env\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\xjp\anaconda3\envs\pytorch_env\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

how to deal with it?

**Comment by amva13** [comment]
have you tried setting path to "./data" or leaving it to None
