### ISSUE TITLE
Load JNK3 Oracle Error

### ISSUE THREAD

**Issue by yuanqidu** [mims-harvard/TDC#93]
Similar erroes occurred for GSK3B, DRD2.

Traceback (most recent call last):
  File "/home/yqdu/moflow-master/data/process_property.py", line 24, in <module>
    jnk3_oracle = Oracle('JNK3')
  File "/home/yqdu/anaconda3/envs/rdkit/lib/python3.9/site-packages/tdc/oracles.py", line 21, in __init__
    self.assign_evaluator() 
  File "/home/yqdu/anaconda3/envs/rdkit/lib/python3.9/site-packages/tdc/oracles.py", line 51, in assign_evaluator
    oracle_object = jnk3()
  File "/home/yqdu/anaconda3/envs/rdkit/lib/python3.9/site-packages/tdc/chem_utils.py", line 597, in __init__
    self.jnk3_model = pickle.load(f)
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

**Comment by yuanqidu** [comment]
sklearn.ensemble.forest was renamed to sklearn.ensemble._forest in https://github.com/scikit-learn/scikit-learn/commit/437ca0553ce8d97571cecc3f4df8493e5cf959c5 on Oct 16, 2019. It requires us to compile the old version from sources, e.g. 0.21.3.

**Comment by yuanqidu** [comment]
Another error I found was in the Deco Hop oracle (below). But the errors did not occur in a similar function Scaffold Hop. I suspect that it was caused by https://github.com/mims-harvard/TDC/blob/master/tdc/chem_utils.py#L1395-L1399 and https://github.com/mims-harvard/TDC/blob/master/tdc/chem_utils.py#L1367 (the if statement). 

There is another error that occurred for Deco_score:
Traceback (most recent call last):
  File "/home/yqdu/moflow-master/data/process_property.py", line 36, in <module>
    deco_hop.append(deco_oracle(smile))
  File "/home/yqdu/anaconda3/envs/rdkit/lib/python3.9/site-packages/tdc/oracles.py", line 251, in __call__
    return self.evaluator_func(*args, **kwargs)
  File "/home/yqdu/anaconda3/envs/rdkit/lib/python3.9/site-packages/tdc/chem_utils.py", line 1382, in deco_hop
    deco1_score = deco1_smarts_scoring(molecule)
NameError: name 'deco1_smarts_scoring' is not defined

**Comment by kexinhuang12345** [comment]
Hi yuanqi, this is indeed due to a version issue with sklearn. We will change the requirements file in the next version. For the next error, @futianfan could you take a look?

**Comment by futianfan** [comment]
sure

**Comment by yuanqidu** [comment]
It looks like the old version is not longer supported by scikit-learn. Could you/May I help to update the function to support the latest scikit-learn version? But it seems like the errors happened during loading the model. Is it possible to re-dump the model with the latest scikit-learn and I believe it will be fixed.

**Comment by futianfan** [comment]
i fixed them, thanks for pointing out!

**Comment by yuanqidu** [comment]
Thanks!

**Comment by futianfan** [comment]
will address the version issue later.
